"""add index on scene episode_id

Revision ID: 4e8200be169b
Revises: d58a74e73066
Create Date: 2026-05-17 22:29:54.180244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8200be169b'
down_revision = 'd58a74e73066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_episode_id'), ['episode_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_episode_id'))

    # ### end Alembic commands ###
