"""Add status column to Episode

Revision ID: 7afddda2e580
Revises: 
Create Date: 2025-04-17 23:45:30.650911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afddda2e580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='لم يبدأ'))
        batch_op.create_index(batch_op.f('ix_episode_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
