"""add scenes and video_generations tables

Revision ID: d58a74e73066
Revises: a91101fbc394
Create Date: 2026-05-17 21:52:40.712521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58a74e73066'
down_revision = '3f9fb79f66ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'number', name='_episode_scene_number_uc')
    )
    op.create_table('video_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=True),
    sa.Column('generate_audio', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('polling_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('unsigned_url', sa.Text(), nullable=True),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_view_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_generation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_generation_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_generation_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_generation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_generation_status'))
        batch_op.drop_index(batch_op.f('ix_video_generation_job_id'))

    op.drop_table('video_generation')
    op.drop_table('scene')
    # ### end Alembic commands ###
