"""Add status column to Episode

Revision ID: e2f85ec20ccf
Revises: 
Create Date: 2025-04-17 22:02:39.595656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f85ec20ccf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='لم يبدأ'))
        batch_op.create_index(batch_op.f('ix_episode_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
