"""add draft fields to scene

Revision ID: f355712d0426
Revises: c1a2b3d4e5f6
Create Date: 2026-05-24 21:16:32.739191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f355712d0426'
down_revision = 'c1a2b3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('draft_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('draft_resolution', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('draft_aspect_ratio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('draft_generate_audio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('draft_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene', schema=None) as batch_op:
        batch_op.drop_column('draft_duration')
        batch_op.drop_column('draft_generate_audio')
        batch_op.drop_column('draft_aspect_ratio')
        batch_op.drop_column('draft_resolution')
        batch_op.drop_column('draft_model')
        batch_op.drop_column('draft_prompt')

    # ### end Alembic commands ###
